"""create initial database

Revision ID: 672a1399dccf
Revises: 
Create Date: 2022-01-21 09:19:58.408638

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '672a1399dccf'
down_revision = None
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_description', table_name='tags')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_table('tags_people')
    op.drop_index('ix_people_name', table_name='people')
    op.drop_table('people')
    op.drop_table('tags_videos')
    op.drop_table('people_videos')
    op.drop_index('ix_videos_file_name', table_name='videos')
    op.drop_index('ix_videos_file_size', table_name='videos')
    op.drop_index('ix_videos_name', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_description', table_name='tags')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_table('tags_people')
    op.drop_index('ix_people_name', table_name='people')
    op.drop_table('people')
    op.drop_table('tags_videos')
    op.drop_table('people_videos')
    op.drop_index('ix_videos_file_name', table_name='videos')
    op.drop_index('ix_videos_file_size', table_name='videos')
    op.drop_index('ix_videos_name', table_name='videos')
    op.drop_table('videos')
    op.create_table('videos',
                    sa.Column('id', sa.INTEGER(), nullable=False, primary_key=True, autoincrement=True),
                    sa.Column('file_name_linux', sa.TEXT(), nullable=True, index=True),
                    sa.Column('file_name_windows', sa.TEXT(), nullable=True, index=True),
                    sa.Column('file_size', sa.BIGINT(), nullable=False, index=True),
                    sa.Column('name', sa.VARCHAR(), nullable=False, index=True),
                    sa.Column('extension', sa.VARCHAR(length=20), nullable=False, default='.mp4'),
                    sa.Column('duration', sa.FLOAT(), nullable=False),
                    sa.Column('is_movie', sa.BOOLEAN(), nullable=False, default=False),
                    sa.Column('file_count', sa.INTEGER(), nullable=True),
                    sa.Column('file_date', sa.DATETIME(), nullable=False),
                    sa.Column('width', sa.INTEGER(), nullable=True, default=854),
                    sa.Column('height', sa.INTEGER(), nullable=True, default=480),
                    sa.Column('frame_rate', sa.FLOAT(), nullable=True),
                    sa.Column('created_at', sa.DATETIME(), nullable=False, default=datetime.now()),
                    sa.Column('updated_at', sa.DATETIME(), nullable=False,
                              default=datetime.now(), onupdate=datetime.now()),
                    )
    #op.create_index('ix_videos_name', 'videos', ['name'], unique=False)
    #op.create_index('ix_videos_file_size', 'videos', ['file_size'], unique=False)
    #op.create_index('ix_videos_file_name_linux', 'videos', ['file_name'])
    #op.create_index('ix_videos_file_name_linux', 'videos', ['file_name'])
    op.create_table('people_videos',
                    sa.Column('id', sa.INTEGER(), nullable=False, primary_key=True, autoincrement=True),
                    sa.Column('video_id', sa.INTEGER(), sa.ForeignKey('videos.id')),
                    sa.Column('person_id', sa.INTEGER(), sa.ForeignKey('people.id')),
                    )
    op.create_table('tags_videos',
                    sa.Column('id', sa.INTEGER(), nullable=False, primary_key=True, autoincrement=True),
                    sa.Column('video_id', sa.INTEGER(), sa.ForeignKey('videos.id')),
                    sa.Column('tag_id', sa.INTEGER(), sa.ForeignKey('tags.id')),
                    )
    op.create_table('people',
                    sa.Column('id', sa.INTEGER(), nullable=False, primary_key=True, autoincrement=True),
                    sa.Column('name', sa.VARCHAR(length=80), nullable=False, index=True, unique=True),
                    sa.Column('count', sa.BIGINT(), nullable=False, default=1),
                    sa.Column('created_at', sa.DATETIME(), nullable=False, default=datetime.now()),
                    sa.Column('updated_at', sa.DATETIME(), nullable=False,
                              default=datetime.now(), onupdate=datetime.now()),
                    )
    #op.create_index('ix_people_name', 'people', ['name'], unique=True)
    op.create_table('tags_people',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('person_id', sa.INTEGER(), sa.ForeignKey('people.id')),
                    sa.Column('tag_id', sa.INTEGER(), sa.ForeignKey('tags.id')),
                    )
    op.create_table('tags',
                    sa.Column('id', sa.INTEGER(), nullable=False, primary_key=True, autoincrement=True),
                    sa.Column('name', sa.VARCHAR(length=10), nullable=False, index=True, unique=True),
                    sa.Column('description', sa.VARCHAR(length=50), nullable=True),
                    sa.Column('created_at', sa.DATETIME(), nullable=False, default=datetime.now()),
                    sa.Column('updated_at', sa.DATETIME(), nullable=False,
                              default=datetime.now(), onupdate=datetime.now()),
                    )
    #op.create_index('ix_tags_name', 'tags', ['name'], unique=True)
    #op.create_index('ix_tags_description', 'tags', ['description'], unique=False)
    # ### end Alembic commands ###
